export const SAMPLE_GET_ALL_SUCCESS = 'SAMPLE_GET_ALL_SUCCESS';
export const SAMPLE_GET_ALL_FAILURE = 'SAMPLE_GET_ALL_FAILURE';
export const SAMPLE_CREATE_SUCCESS = 'SAMPLE_CREATE_SUCCESS';
export const SAMPLE_CREATE_FAILURE = 'SAMPLE_CREATE_FAILURE';
export const SAMPLE_DELETE_SUCCESS = 'SAMPLE_DELETE_SUCCESS';
export const SAMPLE_DELETE_FAILURE = 'SAMPLE_DELETE_FAILURE';

export const INDICES_GET_ALL_SUCCESS = 'INDICES_GET_ALL_SUCCESS';
export const INDICES_GET_ALL_FAILURE = 'INDICES_GET_ALL_FAILURE';

export const CUSTOM_MAPPING_FETCHING_FLAG = 'CUSTOM_MAPPING_FETCHING_FLAG';
export const POPULATE_CUSTOM_MAPPING_SUCCESS = 'POPULATE_CUSTOM_MAPPING_SUCCESS'
export const CUSTOM_MAPPING_CREATE_SUCCESS = 'CUSTOM_MAPPING_CREATE_SUCCESS'
export const TOGGLE_CHECK_BOX = 'TOGGLE_CHECK_BOX'
export const UPDATE_TEXT_BOX = 'UPDATE_TEXT_BOX'

export const SETTINGS_GET_SUCCESS = 'SETTINGS_GET_SUCCESS'
export const SETTINGS_GET_FAILURE = 'SETTINGS_GET_FAILURE'
export const SETTINGS_UPDATE_SUCCESS = 'SETTINGS_UPDATE_SUCCESS'
export const SETTINGS_UPDATE_FAILURE = 'SETTINGS_UPDATE_FAILURE'
export const UPDATE_SEGMENTATION_TEXT_BOX = 'UPDATE_SEGMENTATION_TEXT_BOX'
export const UPDATE_SEGMENTATION_CHECK_BOX = 'UPDATE_SEGMENTATION_CHECK_BOX'
export const UPDATE_SEGMENTATION_NUMBER_BOX = 'UPDATE_SEGMENTATION_NUMBER_BOX'
export const OPERATORS_GET_SUCCESS = 'OPERATORS_GET_SUCCESS'
export const OPERATORS_GET_FAILURE = 'OPERATORS_GET_FAILURE'
export const TOGGLE_RULE_ENGINE_OPERATOR_FORM = 'TOGGLE_RULE_ENGINE_OPERATOR_FORM'
export const TOGGLE_RULE_ENGINE_OPERATOR_LIST = 'TOGGLE_RULE_ENGINE_OPERATOR_LIST'
export const UPDATE_OPERATORS_TEXT_BOX = 'UPDATE_OPERATORS_TEXT_BOX'
export const UPDATE_OPERATORS_NUMBER_BOX = 'UPDATE_OPERATORS_NUMBER_BOX'