export const SAMPLE_GET_ALL_SUCCESS = 'SAMPLE_GET_ALL_SUCCESS';
export const SAMPLE_GET_ALL_FAILURE = 'SAMPLE_GET_ALL_FAILURE';
export const SAMPLE_CREATE_SUCCESS = 'SAMPLE_CREATE_SUCCESS';
export const SAMPLE_CREATE_FAILURE = 'SAMPLE_CREATE_FAILURE';
export const SAMPLE_DELETE_SUCCESS = 'SAMPLE_DELETE_SUCCESS';
export const SAMPLE_DELETE_FAILURE = 'SAMPLE_DELETE_FAILURE';

export const INDICES_GET_ALL_SUCCESS = 'INDICES_GET_ALL_SUCCESS';
export const INDICES_GET_ALL_FAILURE = 'INDICES_GET_ALL_FAILURE';