export const SAMPLE_GET_ALL_SUCCESS = 'SAMPLE_GET_ALL_SUCCESS';
export const SAMPLE_GET_ALL_FAILURE = 'SAMPLE_GET_ALL_FAILURE';
export const SAMPLE_CREATE_SUCCESS = 'SAMPLE_CREATE_SUCCESS';
export const SAMPLE_CREATE_FAILURE = 'SAMPLE_CREATE_FAILURE';